AllCops:
  TargetRubyVersion: 2.2
Documentation:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/ClassVars:
  Exclude:
    - 'spec/**/*.rb'