AllCops:
  TargetRubyVersion: 2.2
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/ClassVars:
  Exclude:
    - 'spec/**/*.rb'